Repository Pive-Guyz/be14-fin-Empick-FE, pull requests merged in 2025-06, with the labels that each got.

#18 [feat] 단일 리스트 컴포넌트 구현
  src/App.vue
  src/components/OneColumnList.vue
  src/router/index.js
  src/views/test/MJOneColumnListTestPage.vue
  src/views/test/MJTestMainPage.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#27 [feat] 모달 창 구현
  package-lock.json
  src/components/common/AlertModal.vue
  src/components/common/Modal.vue
  src/router/index.js
  src/views/WSPage.vue
  src/views/test/CounterPage.vue
  src/views/test/WSPage.vue
Labels: :sparkles: enhancement

#37 [refactor] 달력 디자인 개선
  src/components/common/Calendar.vue
Labels: 🔧 refactoring

#35 [feat] 평가 기준 입력 컴포넌트 생성
  src/components/employment/EvaluationCriteria.vue
  src/router/index.js
  src/views/employment/JobtestPage.vue
  src/views/test/EvaluationTestPage.vue
Labels: :sparkles: enhancement

#39 [feat] login
  src/App.vue
  src/apis/apiClient.js
  src/apis/routes/auth.js
  src/apis/routes/index.js
  src/components/common/MainSidebar.vue
  src/dto/LoginRequestDTO.js
  src/dto/LoginResponseDTO.js
  src/router/index.js
  src/services/authService.js
  src/stores/authStore.js
  src/views/DashboardPage.vue
  src/views/login/LoginPage.vue
Labels: :test_tube: test

#51 [hotfix] 테스트 편의성 향상
  package-lock.json
  src/apis/routes/calculator.js
  src/apis/routes/counter.js
  src/apis/routes/file.js
  src/apis/routes/index.js
  src/apis/routes/mail.js
  src/apis/routes/member.js
  src/dto/auth/loginRequestDTO.js
  src/dto/auth/loginResponseDTO.js
  src/dto/mail/mailRequestDTO.js
  src/dto/member/memberResponseDTO.js
  src/dto/member/memberSignUpRequestDTO.js
  src/router/auth.routes.js
  src/router/employment.routes.js
  src/router/index.js
  src/router/middleware/auth.guard.js
  src/router/orgstructure.routes.js
  src/router/test.routes.js
  src/services/authService.js
  src/services/calculatorService.js
  src/services/counterService.js
  src/services/fileService.js
  src/services/mailService.js
  src/services/memberService.js
  src/stores/calculatorStore.js
  src/stores/counterStore.js
  src/stores/fileStore.js
  src/stores/mailStore.js
  src/stores/memberRegisterStore.js
  src/stores/memberStore.js
  src/views/MainPage.vue
  src/views/login/LoginPage.vue
  src/views/orgstructure/MemberRegisterPage.vue
  src/views/orgstructure/ProfilePage.vue
  src/views/test/CounterPage.vue
Labels: 🚨 HOTFIX

#48 [refactor] 문제 목록 리스트 ListView 컴포넌트 사용
  src/components/common/ListView.vue
  src/components/employment/JobtestListView.vue
  src/dto/common/ApiResponseDTO.js
  src/dto/employment/jobtest/JobtestResponseDTO.js
  src/dto/employment/jobtest/questionResponseDTO.js
  src/router/employment.routes.js
  src/services/jobtestQuestionService.js
  src/stores/jobtestQuestionStore.js
  src/utils/errorHandler.js
  src/views/employment/JobtestQuestionListPage.vue
Labels: 🔧 refactoring

#57 [refactor] 면접 도메인 API 요청 라우팅 설정 / 각 도메인 반환 DTO, Service, Store 구현
  src/apis/routes/index.js
  src/apis/routes/interview.js
  src/dto/employment/interview/interviewCriteriaResponseDTO.js
  src/dto/employment/interview/interviewResponseDTO.js
  src/dto/employment/interview/interviewScoreResponseDTO.js
  src/dto/employment/interview/interviewSheetItemResponseDTO.js
  src/dto/employment/interview/interviewSheetResponseDTO.js
  src/dto/employment/interview/interviewerResponseDTO.js
  src/services/interviewCriteriaService.js
  src/services/interviewScoreService.js
  src/services/interviewService.js
  src/services/interviewSheetItemService.js
  src/services/interviewSheetService.js
  src/services/interviewerService.js
  src/stores/interviewCriteriaStore.js
  src/stores/interviewScoreStore.js
  src/stores/interviewSheetItemStore.js
  src/stores/interviewSheetStore.js
  src/stores/interviewStore.js
  src/stores/interviewerStore.js
Labels: 🔧 refactoring

#54 [feat] 채용요청서 목록 페이지 구현 / [refactor] App.vue 수정
  src/App.vue
  src/apis/routes/index.js
  src/apis/routes/recruitment.js
  src/components/common/Header.vue
  src/components/common/MainSidebar.vue
  src/dto/employment/recruitment/RecruitmentRequestResponseDTO.js
  src/json/fullMenu.js
  src/router/auth.routes.js
  src/router/employment.routes.js
  src/router/index.js
  src/services/recruitmentService.js
  src/stores/recruitmentStore.js
  src/views/employment/RecruitmentRequestCreateView.vue
  src/views/employment/RecruitmentRequestDetailPage.vue
  src/views/employment/RecruitmentRequestListPage.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#62 [feat] 사원 : 내 정보 조회, 프로필 사진 변경, 사원 등록시 이메일 안내
  jsconfig.json
  src/apis/apiClient.js
  src/apis/routes/member.js
  src/components/common/AlertModal.vue
  src/dto/common/apiResponseDTO.js
  src/dto/employment/mail/mailRequestDTO.js
  src/dto/mail/mailRequestDTO.js
  src/services/authService.js
  src/services/fileService.js
  src/services/interviewCriteriaService.js
  src/services/interviewScoreService.js
  src/services/interviewService.js
  src/services/interviewSheetItemService.js
  src/services/interviewSheetService.js
  src/services/interviewerService.js
  src/services/mailService.js
  src/services/mailTemplateService.js
  src/services/memberService.js
  src/stores/memberRegisterStore.js
  src/stores/memberStore.js
  src/views/orgstructure/MemberRegisterPage.vue
  src/views/orgstructure/ProfilePage.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#67 [feat] 실무테스트 문제 등록 페이지 구현
  src/components/employment/DescriptiveQuestionForm.vue
  src/components/employment/MultipleQuestionForm.vue
  src/components/employment/SubjectiveForm.vue
  src/dto/employment/jobtest/createGradingCriteriaRequestDTO.js
  src/dto/employment/jobtest/createQuestionOptionRequestDTO.js
  src/dto/employment/jobtest/createQuestionRequestDTO.js
  src/services/jobtestQuestionService.js
  src/views/employment/JobtestQuestionCreatePage.vue
Labels: :sparkles: enhancement

#69 [feat] 실무테스트 목록 조회 페이지 구현
  src/dto/employment/jobtest/jobtestListResponseDTO.js
  src/services/jobtestService.js
  src/stores/jobtestListStore.js
  src/views/employment/JobtestListPage.vue
Labels: :sparkles: enhancement

#75 [hotfix][refactor] DB 수정 및 백엔드 변경에 따른 프론트 라우팅 및 DTO 변경
  src/apis/routes/interview.js
  src/dto/employment/interview/interviewCriteriaResponseDTO.js
  src/dto/employment/interview/interviewResponseDTO.js
  src/dto/employment/interview/interviewScoreResponseDTO.js
  src/dto/employment/interview/interviewSheetItemResponseDTO.js
  src/dto/employment/interview/interviewSheetResponseDTO.js
  src/dto/employment/interview/interviewerResponseDTO.js
  src/services/interviewCriteriaService.js
  src/services/interviewerService.js
Labels: 🚨 HOTFIX, 🔧 refactoring

#70 [feat] 채용 요청서 상세 조회, 등록 페이지 구현
  src/apis/routes/recruitment.js
  src/components/employment/TemplateYNModal.vue
  src/dto/employment/recruitment/RecruitmentRequestCreateDTO.js
  src/dto/employment/recruitment/RecruitmentRequestResponseDTO.js
  src/router/employment.routes.js
  src/services/recruitmentRequestService.js
  src/stores/recruitmentRequestStore.js
  src/stores/recruitmentStore.js
  src/views/employment/RecruitmentRequestCreateView.vue
  src/views/employment/RecruitmentRequestDetailPage.vue
  src/views/employment/RecruitmentRequestListPage.vue
Labels: :sparkles: enhancement

#73 !hotfix : 대쉬보드로 페이지 링크 병합
  src/views/DashboardPage.vue
Labels: :test_tube: test

#80 [feat] 안내 메일 발송 모달 기능 구현
  src/components/mail/SendMailModal.vue
  src/views/test/MJTestMainPage.vue
Labels: :sparkles: enhancement

#81 [feat] 실무테스트 등록 페이지 구현
  src/components/employment/QuestionCreateModal.vue
  src/dto/employment/jobtest/createJobtestQuestionRequestDTO.js
  src/dto/employment/jobtest/createJobtestRequestDTO.js
  src/services/jobtestService.js
  src/stores/jobtestQuestionStore.js
  src/views/employment/JobtestCreatePage.vue
  src/views/employment/JobtestQuestionCreatePage.vue
  src/views/employment/JobtestQuestionListPage.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#82 [featire] 문제 상세 조회 페이지 구현
  src/components/employment/JobtestQuestionDetailModal.vue
  src/dto/employment/jobtest/answerResponseDTO.js
  src/dto/employment/jobtest/questionDetailResponseDTO.js
  src/router/employment.routes.js
  src/services/answerService.js
  src/services/jobtestQuestionService.js
  src/stores/answerStore.js
  src/views/employment/JobtestAnswerDetailPage.vue
Labels: :sparkles: enhancement

#78 [feat] 면접 평가표 등록 페이지 구현
  src/components/OneColumnList.vue
  src/components/mail/SendMailModal.vue
  src/router/employment.routes.js
  src/router/index.js
  src/services/interviewSheetItemService.js
  src/services/interviewerService.js
  src/views/employment/CreateInterviewSheetPage.vue
  src/views/employment/InterviewCriteriaPage.vue
  src/views/employment/InterviewSheetPage.vue
Labels: :sparkles: enhancement

#83 [feat] 채용공고 목록, 상세조회 페이지 구현
  src/apis/routes/recruitment.js
  src/constants/employment/inputTypes.js
  src/constants/employment/recruitStatus.js
  src/constants/employment/recruitTypes.js
  src/dto/employment/recruitment/applicationItemDTO.js
  src/dto/employment/recruitment/recruitmentDetailResponseDTO.js
  src/dto/employment/recruitment/recruitmentProcessDTO.js
  src/dto/employment/recruitment/recruitmentResponseDTO.js
  src/json/fullMenu.js
  src/router/employment.routes.js
  src/services/recruitmentService.js
  src/stores/recruitmentStore.js
  src/views/employment/RecruitmentCreatePage.vue
  src/views/employment/RecruitmentDetailPage.vue
  src/views/employment/RecruitmentListPage.vue
  src/views/employment/RecruitmentRequestCreateView.vue
  src/views/employment/RecruitmentRequestDetailPage.vue
  src/views/employment/RecruitmentRequestListPage.vue
Labels: :sparkles: enhancement

#90 [feat] 지원서 상세 정보 페이지 구현
  src/components/employment/IntroduceResult.vue
  src/json/fullMenu.js
  src/router/employment.routes.js
  src/views/employment/ApplicantPage.vue
  src/views/employment/ApplicationPage.vue
Labels: :sparkles: enhancement

#84 [feat] 채용공고 조회 시, 해당 공고의 프로세스 조회 추가
  src/apis/routes/recruitment.js
  src/constants/employment/stepType.js
  src/dto/employment/recruitment/recruitmentProcessDTO.js
  src/router/employment.routes.js
  src/services/recruitmentProcessService.js
  src/services/recruitmentRequestService.js
  src/stores/recruitmentProcessStore.js
  src/views/employment/RecruitmentDetailPage.vue
Labels: :sparkles: enhancement

#93 [feat] 지원서 / 지원자 도메인 api / DTO / service / store 구현
  src/apis/routes/application.js
  src/dto/employment/application/applicantResponseDTO.js
  src/dto/employment/application/applicationResponeDTO.js
  src/router/employment.routes.js
  src/services/applicantService.js
  src/services/applicationService.js
  src/stores/applicantStore.js
  src/stores/applicationStore.js
Labels: :sparkles: enhancement, 🚨 HOTFIX

#91 [feat] 채용공고 등록 페이지 구현
  package.json
  src/apis/routes/recruitment.js
  src/constants/employment/recruitTypes.js
  src/dto/employment/recruitment/applicationItemCategoryDTO.js
  src/dto/employment/recruitment/recruitmentCreateDTO.js
  src/main.js
  src/router/employment.routes.js
  src/services/applicationItemService.js
  src/services/recruitmentService.js
  src/stores/applicationItemStore.js
  src/stores/recruitmentStore.js
  src/views/employment/ApplicationItemSelectPage.vue
  src/views/employment/RecruitmentCreatePage.vue
  src/views/employment/RecruitmentDetailPage.vue
Labels: :sparkles: enhancement

#92 !hotfix : eslint 적용 (MVVM 패턴 강제)
  eslint.config.js
  package-lock.json
  package.json
Labels: :sparkles: enhancement

#95 [refactor] 문제 상세 보기 - 선택지에 정답 표시
  src/components/employment/JobtestQuestionDetailModal.vue
  src/views/employment/JobtestQuestionListPage.vue
Labels: 🎨 design, 🔧 refactoring

#85 [feat] 면접 평가표 조회 페이지 - 등록 - 최신화 기능 구현
  src/apis/routes/interview.js
  src/router/employment.routes.js
  src/services/interviewCriteriaService.js
  src/stores/interviewCriteriaStore.js
  src/stores/interviewScoreStore.js
  src/stores/interviewSheetItemStore.js
  src/stores/interviewSheetStore.js
  src/stores/interviewStore.js
  src/stores/interviewerStore.js
  src/views/employment/CreateInterviewSheetPage.vue
  src/views/employment/InterviewCriteriaPage.vue
  src/views/employment/InterviewSheetPage.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#88 [feat] 지원서 목록 + 면접 상세 정보 페이지 기능 구현 + 면접 정보 수정 기능 구현
  src/apis/routes/index.js
  src/apis/routes/interview.js
  src/dto/employment/application/applicantResponseDTO.js
  src/dto/employment/application/applicationResponeDTO.js
  src/router/employment.routes.js
  src/services/applicantService.js
  src/services/applicationService.js
  src/services/interviewCriteriaService.js
  src/services/interviewService.js
  src/stores/applicantStore.js
  src/stores/applicationStore.js
  src/stores/interviewCriteriaStore.js
  src/stores/interviewStore.js
  src/views/employment/CreateInterviewPage.vue
  src/views/employment/InterviewDetailPage.vue
  src/views/employment/InterviewPage.vue
  src/views/employment/InterviewSheetPage.vue
Labels: :sparkles: enhancement

#107 [feat] 실무테스트 문제 삭제 기능 추가
  src/components/common/ListView.vue
  src/services/jobtestQuestionService.js
  src/stores/jobtestQuestionStore.js
  src/views/employment/JobtestQuestionListPage.vue
Labels: :sparkles: enhancement

#104 [feat] 결재 메뉴 주소 연결 및 페이지 틀 생성
  src/json/fullMenu.js
  src/router/approval.routes.js
  src/router/index.js
  src/views/approval/ApprovalCreatePage.vue
  src/views/approval/ApprovalDetailPage.vue
  src/views/approval/ApprovalInboxPage.vue
  src/views/approval/ApprovalSentPage.vue
Labels: :sparkles: enhancement

#125 [refactor] 문제, 실무테스트 생성자 실제 로그인한 회원 id 연동
  src/components/employment/QuestionCreateModal.vue
  src/views/employment/JobtestCreatePage.vue
  src/views/employment/JobtestQuestionCreatePage.vue
Labels: :sparkles: enhancement

#128 [feat] 면접 등록 기능 구현
  src/components/employment/InterviewSheetModal.vue
  src/router/employment.routes.js
  src/views/employment/CreateInterviewPage.vue
  src/views/employment/InterviewSchedulePage.vue
Labels: :sparkles: enhancement

#126 [feat] 지원자 목록 데이터 바인딩
  package-lock.json
  src/apis/routes/applicant.js
  src/apis/routes/application.js
  src/components/common/Header.vue
  src/components/common/Search.vue
  src/dto/employment/applicant/applicantFullInfoListDTO.js
  src/router/employment.routes.js
  src/services/applicantService.js
  src/stores/applicantStore.js
  src/views/employment/ApplicantPage.vue
  src/views/employment/ApplicationPage.vue
  src/views/orgstructure/MemberRegisterPage.vue
Labels: :sparkles: enhancement

#132 [refactor] [hotfix] 라우팅 변수 이름 형태 및 반환 객체 타입 수정
  src/dto/common/apiResponseDTO.js
  src/dto/employment/jobtest/createApplicationJobtestDTO.js
  src/dto/employment/mail/interviewMailResponseDTO.js
  src/dto/employment/mail/jobtestMailResponseDTO.js
  src/dto/employment/mail/mailTemplateResponseDTO.js
  src/dto/employment/recruitment/applicationItemCategoryDTO.js
  src/dto/employment/recruitment/applicationItemDTO.js
  src/dto/employment/recruitment/recruitmentCreateDTO.js
  src/dto/employment/recruitment/recruitmentDetailResponseDTO.js
  src/dto/employment/recruitment/recruitmentResponseDTO.js
  src/services/applicantService.js
  src/services/applicationItemService.js
  src/services/applicationService.js
  src/services/interviewCriteriaService.js
  src/services/interviewerService.js
  src/services/mailService.js
  src/services/mailTemplateService.js
  src/views/employment/ApplicantPage.vue
  src/views/test/ApplicationAssignTestPage.vue
Labels: 🚨 HOTFIX, 🔧 refactoring

#130 [feat] 지원자 일괄 사원 등록 + 사원 검색 service
  src/apis/routes/member.js
  src/services/memberService.js
  src/stores/memberRegisterStore.js
  src/stores/memberStore.js
  src/views/orgstructure/MemberRegisterPage.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#131 [feat] 결재 요청서 작성 / [refactor] 부서, 직무 조회 채용 공고에서 분리
  src/apis/routes/approval.js
  src/constants/common/inputType.js
  src/dto/approval/approval/createApprovalDTO.js
  src/dto/approval/approvalCategory/approvalCategoryDTO.js
  src/dto/approval/approvalCategoryItem/approvalCategoryItemDTO.js
  src/services/approvalService.js
  src/services/departmentService.js
  src/services/jobService.js
  src/services/recruitmentRequestService.js
  src/stores/approvalFormStore.js
  src/stores/approvalWriteStore.js
  src/stores/departmentStore.js
  src/stores/jobStore.js
  src/stores/recruitmentRequestStore.js
  src/views/approval/ApprovalCreatePage.vue
Labels: :sparkles: enhancement

#109 [feat] 자기소개서 페이지 연동 ( 템플릿,상세페이지,작성페이지,항목페이지)
  src/components/employment/IntroduceEvaluationInput.vue
  src/constants/common/fullMenu.js
  src/dto/employment/applicant/applicantListRequestDTO.js
  src/dto/employment/applicant/applicantListResponseDTO.js
  src/dto/employment/applicant/applicantResponseDTO.js
  src/dto/employment/applicant/applicationCommandDTO.js
  src/dto/employment/applicant/applicationResponseDTO.js
  src/router/employment.routes.js
  src/services/applicantService.js
  src/services/applicationService.js
  src/services/introduceService.js
  src/services/introduceTemplateItemService.js
  src/services/introduceTemplateService.js
  src/stores/introduceItemStore.js
  src/stores/introduceStore.js
  src/stores/introduceTemplateStore.js
  src/views/employment/ApplicantPage.vue
  src/views/employment/ApplicantRegistrationPage.vue
  src/views/employment/ApplicationPage.vue
  src/views/employment/IntroduceStandardItemManagePage.vue
  src/views/employment/IntroduceStandardItemPage.vue
  src/views/employment/IntroduceTemplateCreatePage.vue
  src/views/employment/IntroduceTemplateDetailPage.vue
  src/views/employment/IntroduceTemplateListPage.vue
Labels: :sparkles: enhancement

#137 [refactor] 채용공고 템플릿 제외 및 헤더 수정
  src/App.vue
  src/components/common/Header.vue
  src/constants/common/fullMenu.js
  src/views/employment/RecruitmentRequestDetailPage.vue
Labels: 🔧 refactoring

#139 [refactor] 요청받은 결재 목록 페이지 필터링 추가/헤더 드롭다운 위치 조정
  src/components/common/Header.vue
  src/constants/approval/approvalStatus.js
  src/dto/employment/recruitment/recruitmentDetailResponseDTO.js
  src/services/recruitmentService.js
  src/views/approval/ApprovalInboxPage.vue
Labels: 🔧 refactoring

#147 [refactor] 결재문서 로딩 오류 해결 및 컴포넌트 수정
  package.json
  src/components/common/Header.vue
  src/components/common/ListView.vue
  src/main.js
  src/stores/approvalStore.js
  src/stores/authStore.js
  src/stores/memberStore.js
  src/views/approval/ApprovalInboxPage.vue
  src/views/approval/ApprovalSentPage.vue
  src/views/employment/RecruitmentListPage.vue
  src/views/employment/RecruitmentRequestListPage.vue
Labels: 🔧 refactoring

#148 [feat] 실무테스트 응시 페이지 구현
  src/apis/routes/jobtest.js
  src/components/employment/ExamSidebar.vue
  src/components/employment/JobtestApplicantTable.vue
  src/components/employment/MultipleChoice.vue
  src/components/employment/QuestionView.vue
  src/components/employment/ShortAnswer.vue
  src/constants/common/fullMenu.js
  src/constants/employment/questionTypes.js
  src/dto/employment/jobtest/answerRequestDTO.js
  src/main.js
  src/router/employment.routes.js
  src/services/answerService.js
  src/services/jobtestService.js
  src/stores/answerStore.js
  src/stores/jobtestEntryStore.js
  src/stores/jobtestExamStore.js
  src/views/employment/JobtestCreatePage.vue
  src/views/employment/JobtestDetailPage.vue
  src/views/employment/JobtestEnterPage.vue
  src/views/employment/JobtestExamPage.vue
Labels: :sparkles: enhancement

#151 [refactor] 사원 등록 프로필 이미지 업로드 방식 변경
  src/apis/apiClient.js
  src/apis/routes/member.js
  src/components/attendance/WeekSummaryCard.vue
  src/components/common/CircleLoading.vue
  src/dto/member/memberSignUpRequestDTO.js
  src/services/memberService.js
  src/stores/memberRegisterStore.js
  src/stores/memberStore.js
  src/views/orgstructure/MemberRegisterPage.vue
Labels: 🔧 refactoring

#154 [feat] 결재문서 상세 조회 페이지 구현/ 승인,반려 연동
  src/apis/routes/approval.js
  src/components/common/ListView.vue
  src/dto/approval/approval/approvalReceivedDetailDTO.js
  src/dto/approval/approval/approvalRequestedDetailDTO.js
  src/router/approval.routes.js
  src/services/approvalService.js
  src/stores/approvalStore.js
  src/views/approval/ApprovaRequestedDetailPage.vue
  src/views/approval/ApprovalDetailPage.vue
  src/views/approval/ApprovalInboxPage.vue
  src/views/approval/ApprovalReceivedDetailPage.vue
  src/views/approval/ApprovalSentPage.vue
Labels: :sparkles: enhancement

#156 [feat] 안내 메일 도메인 페이지 구현 / 메일 발송 기능 구현
  src/apis/routes/mail.js
  src/components/mail/EmailPreviewModal.vue
  src/components/mail/SelectEmailModal.vue
  src/constants/common/fullMenu.js
  src/router/employment.routes.js
  src/services/mailService.js
  src/stores/mailStore.js
  src/views/employment/ApplicantPage.vue
  src/views/employment/EmailHistoryPage.vue
  src/views/employment/MailPage.vue
  src/views/employment/SendEmailPage.vue
Labels: :sparkles: enhancement

#157 [feat] 채용 공고 수정 페이지 구현
  src/apis/routes/introduce.js
  src/constants/employment/stepType.js
  src/router/employment.routes.js
  src/services/recruitmentService.js
  src/stores/approvalStore.js
  src/stores/recruitmentStore.js
  src/views/approval/ApprovaRequestedDetailPage.vue
  src/views/approval/ApprovalInboxPage.vue
  src/views/approval/ApprovalReceivedDetailPage.vue
  src/views/approval/ApprovalSentPage.vue
  src/views/employment/ApplicationItemSelectPage.vue
  src/views/employment/RecruitmentCreatePage.vue
  src/views/employment/RecruitmentDetailPage.vue
  src/views/employment/RecruitmentListPage.vue
  src/views/employment/RecruitmentPage.vue
  src/views/employment/RecruitmentRequestListPage.vue
  src/views/employment/RecruitmentUpdatePage.vue
Labels: :sparkles: enhancement

#159 [feat] 채용요청 결재 완료 시 채용요청서 연동 기능 구현
  src/services/recruitmentRequestService.js
  src/stores/recruitmentRequestStore.js
  src/views/approval/ApprovaRequestedDetailPage.vue
  src/views/approval/ApprovalCreatePage.vue
  src/views/approval/ApprovalReceivedDetailPage.vue
  src/views/employment/RecruitmentCreatePage.vue
Labels: :sparkles: enhancement

#160 [refactor] 실무테스트 관련 기능 추가 및 수정
  src/components/common/Modal.vue
  src/components/employment/JobtestQuestionDetailModal.vue
  src/dto/employment/jobtest/jobtestRequestDTO.js
  src/services/jobtestService.js
  src/stores/jobtestDetailStore.js
  src/stores/jobtestListStore.js
  src/stores/jobtestQuestionStore.js
  src/views/employment/JobtestCreatePage.vue
  src/views/employment/JobtestDetailPage.vue
  src/views/employment/JobtestListPage.vue
  src/views/employment/JobtestQuestionFormPage.vue
  src/views/employment/JobtestQuestionListPage.vue
Labels: :sparkles: enhancement

#169 [hotfix] 근태, 메뉴 인사 라우팅 수정
  src/components/attendance/AttendanceSummaryCard.vue
  src/composables/useAttendanceDetail.js
  src/composables/useMemberList.js
  src/config/attendance/businessRules.js
  src/config/attendance/constants.js
  src/constants/common/fullMenu.js
  src/dto/attendance/attendanceCategoryRequestDTO.js
  src/dto/attendance/attendanceRecordCreateRequestDTO.js
  src/dto/attendance/attendanceRecordResponseDTO.js
  src/stores/attendanceStore.js
  src/utils/attendance/attendanceCalculator.js
  src/utils/memberUtils.js
  src/views/MainPage.vue
Labels: 🚨 HOTFIX

#165 [feat] 지원서에 자소서 연동 성공 / 자기소개서 평가 결과 등록 연동 성공 / 평가 절차에 등록된 데이터 조회 연동 / 평가결과서 데이터 상시 조회 연동 / 전형절차에서도 조회 연동
  src/apis/routes/introduce.js
  src/components/employment/IntroduceEvaluationInput.vue
  src/constants/employment/applicationStatus.js
  src/dto/employment/application/applicationResponeDTO.js
  src/services/applicationService.js
  src/services/introduceService.js
  src/services/introduceStandardItemService.js
  src/stores/applicationStore.js
  src/utils/errorHandler.js
  src/views/employment/ApplicantPage.vue
  src/views/employment/ApplicationPage.vue
  src/views/employment/IntroduceStandardItemManagePage.vue
Labels: :sparkles: enhancement

#166 [feat] 지원서 상태 변경 연동
  src/apis/routes/introduce.js
  src/components/employment/IntroduceEvaluationInput.vue
  src/constants/employment/applicationStatus.js
  src/dto/employment/application/applicationResponeDTO.js
  src/services/applicationService.js
  src/services/introduceService.js
  src/services/introduceStandardItemService.js
  src/stores/applicationStore.js
  src/utils/errorHandler.js
  src/views/employment/ApplicantPage.vue
  src/views/employment/ApplicationPage.vue
  src/views/employment/IntroduceStandardItemManagePage.vue
Labels: :sparkles: enhancement

#167 [ref] 페이지 디자인 수정
  src/views/career/CareerRecruitmentDetail.vue
  src/views/career/CareerRecruitmentList.vue
  src/views/career/CareerResumePage.vue
  src/views/employment/IntroduceStandardCreatePage.vue
  src/views/employment/IntroduceStandardItemManagePage.vue
Labels: 🎨 design, 🔧 refactoring

#170 [fix] 발표전 오류나는 부분 수정
  src/components/employment/JobtestQuestionDetailModal.vue
  src/components/employment/JobtestQuestionList.vue
  src/components/employment/JobtestSelectModal.vue
  src/components/employment/JobtestSummaryCard.vue
  src/components/employment/MultipleChoice.vue
  src/components/employment/MultipleQuestionForm.vue
  src/components/employment/QuestionCreateModal.vue
  src/components/employment/QuestionView.vue
  src/components/employment/ShortAnswer.vue
  src/components/employment/SubjectiveForm.vue
  src/constants/employment/difficulty.js
  src/constants/employment/questionTypes.js
  src/dto/approval/approvalCategory/approvalCategoryDTO.js
  src/dto/employment/jobtest/jobtestDetailDTO.js
  src/dto/employment/jobtest/jobtestDetailResponseDTO.js
  src/router/employment.routes.js
  src/router/index.js
  src/services/answerService.js
  src/services/approvalService.js
  src/services/jobtestService.js
  src/stores/applicantStore.js
  src/stores/approvalWriteStore.js
  src/stores/jobtestExamStore.js
  src/stores/jobtestQuestionStore.js
  src/utils/errorHandler.js
  src/views/approval/ApprovalCreatePage.vue
  src/views/employment/ApplicantPage.vue
  src/views/employment/JobtestAnswerDetailPage.vue
  src/views/employment/JobtestCreatePage.vue
  src/views/employment/JobtestDetailPage.vue
  src/views/employment/JobtestEnterPage.vue
  src/views/employment/JobtestExamPage.vue
  src/views/employment/JobtestListPage.vue
  src/views/employment/JobtestQuestionFormPage.vue
  src/views/employment/JobtestQuestionListPage.vue
  src/views/errors/ForbiddenPage.vue
  src/views/errors/NotFoundPage.vue
Labels: :bug: bug, 🎨 design, :sparkles: enhancement, 🔧 refactoring

#172 [feat] 지원서 상세 페이지 면접 점수 조회 기능 구현
  src/views/employment/ApplicationPage.vue
  src/views/login/LoginPage.vue
Labels: :sparkles: enhancement

#177 [refactor] 면접 일정 페이지 디자인 개선 / 면접 평가표 페이지 디자인 개선
  src/components/common/InterviewScheduleCalendar.vue
  src/views/employment/CreateInterviewSheetPage.vue
  src/views/employment/InterviewSchedulePage.vue
  src/views/employment/InterviewSheetPage.vue
Labels: 🎨 design, 🔧 refactoring

#178 [refactor] 안내 메일 발송 페이지 디자인 개선
  src/views/employment/SendEmailPage.vue
Labels: 🎨 design, 🔧 refactoring

#182 !hotfix : 로그아웃 무한 루프
  src/App.vue
  src/apis/apiClient.js
  src/services/authService.js
  src/stores/authStore.js
  src/utils/errorHandler.js
  src/views/MainPage.vue
Labels: 🚨 HOTFIX

#184 [refactor] 안내 메일 발송 화면 재구성
  src/router/employment.routes.js
  src/views/employment/ApplicantPage.vue
  src/views/employment/ApplicationPage.vue
  src/views/employment/SendEmailPage.vue
Labels: 🎨 design, 🔧 refactoring

#188 [refactor] 실무테스트 수정 구현
  src/views/employment/JobtestCreatePage.vue
  src/views/employment/JobtestDetailPage.vue
Labels: :bug: bug, 🔧 refactoring

#190 [refactor] 면접관 이름 표시
  src/stores/memberStore.js
  src/views/employment/InterviewDetailPage.vue
Labels: 🎨 design, 🔧 refactoring

#185 [feat] 지원자 목록 페이지 필터링 기능 추가
  src/views/employment/ApplicantPage.vue
Labels: :sparkles: enhancement

#191 [refactor] 채용공고 등록 시 지원서 항목 필수여부 반영 오류 수정 / 채용공고별 지원자 처리 상태 수정
  src/views/employment/ApplicantRecruitmentPage.vue
  src/views/employment/ApplicationItemSelectPage.vue
Labels: 🔧 refactoring

#192 [refactor] 면접 도메인 페이지 디자인 수정
  src/components/employment/InterviewEvaluationCriteria.vue
  src/components/employment/InterviewSheetModal.vue
  src/stores/interviewStore.js
  src/views/employment/CreateInterviewPage.vue
  src/views/employment/InputInterviewScorePage.vue
Labels: 🎨 design, 🔧 refactoring

#196 [refactor] 채용공고 프로세스 디자인 변경
  src/views/employment/RecruitmentCreatePage.vue
  src/views/employment/RecruitmentDetailPage.vue
  src/views/employment/RecruitmentUpdatePage.vue
Labels: 🔧 refactoring

#198 [feat] 시험 시간 연동 + 실제로 움직이게
  src/views/employment/ApplicationPage.vue
  src/views/employment/JobtestExamPage.vue
Labels: :sparkles: enhancement

#199 [refactor] 지원서 페이지 면접관 이름 표시
  src/views/employment/ApplicationPage.vue
Labels: 🔧 refactoring

#197 [ref] 지원서 상태 변경 관련 리펙토링
  src/components/employment/IntroduceEvaluationInput.vue
  src/stores/applicationStore.js
  src/views/career/CareerResumePage.vue
  src/views/employment/ApplicationPage.vue
  src/views/employment/IntroduceStandardCreatePage.vue
  src/views/employment/IntroduceStandardItemManagePage.vue
  src/views/employment/IntroduceStandardListPage.vue
  src/views/employment/IntroduceTemplateCreatePage.vue
  src/views/employment/IntroduceTemplateItemManagePage.vue
  src/views/employment/IntroduceTemplateListPage.vue
Labels: :bug: bug, 🔧 refactoring

#201 [refactor] 사이드바에 다크모드 토글 삭제
  src/components/common/MainSidebar.vue
Labels: 🎨 design, 🔧 refactoring

#204 [bug] 지원서 등록 관련 버그 수정
  src/dto/employment/applicant/applicationCommandDTO.js
  src/dto/employment/application/applicantResponseDTO.js
  src/dto/employment/application/applicationResponeDTO.js
  src/services/applicationService.js
  src/services/introduceService.js
  src/stores/introduceStore.js
  src/views/career/CareerResumePage.vue
Labels: :bug: bug, 🔧 refactoring

#202 [refactor] 채용공고 목록에서 작성 버튼 삭제
  src/views/employment/RecruitmentCreatePage.vue
  src/views/employment/RecruitmentListPage.vue
Labels: 🔧 refactoring

#203 [refactor] 알림 창 토스트팝업 형식으로 통일
  src/views/employment/CreateInterviewPage.vue
  src/views/employment/CreateInterviewSheetPage.vue
  src/views/employment/InputInterviewScorePage.vue
  src/views/employment/InterviewDetailPage.vue
  src/views/employment/InterviewSchedulePage.vue
  src/views/employment/InterviewSheetPage.vue
Labels: 🎨 design, 🔧 refactoring

#205 [refactor] 토스트 한번만 나오게 / 모달 확인 버튼만 나오게
  src/components/employment/JobtestQuestionDetailModal.vue
  src/components/employment/QuestionCreateModal.vue
  src/stores/jobtestDetailStore.js
  src/views/employment/ApplicantPage.vue
  src/views/employment/JobtestAnswerDetailPage.vue
  src/views/employment/JobtestCreatePage.vue
  src/views/employment/JobtestDetailPage.vue
  src/views/employment/JobtestEnterPage.vue
  src/views/employment/JobtestExamPage.vue
  src/views/employment/JobtestListPage.vue
  src/views/employment/JobtestQuestionFormPage.vue
  src/views/employment/JobtestQuestionListPage.vue
Labels: 🔧 refactoring

#206 [feat] 지원자 페이지용 에러페이지 생성 / [design] 지원자 페이지 CSS 수정
  src/constants/common/fullMenu.js
  src/router/index.js
  src/router/middleware/auth.guard.js
  src/utils/errorHandler.js
  src/views/career/ApplicantRegisterPage.vue
  src/views/career/CareerRecruitmentDetail.vue
  src/views/career/CareerRecruitmentList.vue
  src/views/career/CareerResumePage.vue
  src/views/career/CareerWelfarePage.vue
  src/views/errors/CareerErrorPage.vue
  src/views/errors/NotFoundPage.vue
Labels: :sparkles: enhancement

#207 [refactor] 평가표 생성 memberId 들어가게 기능 리팩토링
  src/views/employment/CreateInterviewSheetPage.vue
Labels: 🔧 refactoring

#208 [design] 자기소개서 템플릿/평가 관련 페이지 css수정
  src/views/employment/IntroduceStandardCreatePage.vue
  src/views/employment/IntroduceStandardDetailPage.vue
  src/views/employment/IntroduceStandardItemCreatePage.vue
  src/views/employment/IntroduceStandardItemManagePage.vue
  src/views/employment/IntroduceStandardItemPage.vue
  src/views/employment/IntroduceStandardListPage.vue
  src/views/employment/IntroduceTemplateCreatePage.vue
  src/views/employment/IntroduceTemplateDetailPage.vue
  src/views/employment/IntroduceTemplateItemManagePage.vue
  src/views/employment/IntroduceTemplateListPage.vue
Labels: 🎨 design

#209 [refactor] 결재 페이지 모달,토스트 통일 / fullMenu 수정
  src/components/common/MainSidebar.vue
  src/constants/common/fullMenu.js
  src/views/approval/ApprovalReceivedDetailPage.vue
Labels: 🔧 refactoring

#213 [!hotfix] 실무테스트/결재 버그 수정
  src/dto/employment/jobtest/jobtestRequestDTO.js
  src/views/approval/ApprovalCreatePage.vue
  src/views/employment/JobtestCreatePage.vue
Labels: :bug: bug, 🎨 design, 🚨 HOTFIX

#214 [refactor] 채용 프로세스 오류 수정
  src/views/employment/RecruitmentCreatePage.vue
  src/views/employment/RecruitmentUpdatePage.vue
Labels: 🔧 refactoring

#215 [refactor] 면접 도메인 창 헤더 너비 조정
  src/views/employment/CreateInterviewPage.vue
  src/views/employment/CreateInterviewSheetPage.vue
  src/views/employment/InputInterviewScorePage.vue
  src/views/employment/InterviewDetailPage.vue
Labels: 🔧 refactoring

#219 !hotfix : 발표전 제기된 모든 이슈 수정
  .github/workflows/deploy-frontend.yml
  index.html
  src/components/attendance/AttendanceSummaryCard.vue
  src/components/common/Header.vue
  src/components/common/MainSidebar.vue
  src/composables/useProfileImage.js
  src/constants/common/fullMenu.js
  src/router/index.js
  src/router/myinfo.routes.js
  src/services/memberService.js
  src/views/attendance/AttendanceDetailPage.vue
  src/views/orgstructure/MemberRegisterPage.vue
  src/views/orgstructure/ProfilePage.vue
Labels: 🚨 HOTFIX

#220 [ref] 지원자 목록 정렬 오류 수정
  src/composables/useApplicantManager.js
  src/stores/applicantStore.js
  src/views/employment/ApplicantPage.vue
Labels: 🔧 refactoring

#221 [feat] 사원 근태 기록 페이지 + 사원 기본 정보 수정
  src/apis/routes/member.js
  src/components/common/Header.vue
  src/composables/useAttendanceDetail.js
  src/composables/useMemberList.js
  src/composables/useProfileForm.js
  src/services/memberService.js
  src/stores/memberStore.js
  src/utils/attendanceUtils.js
  src/utils/memberUtils.js
  src/views/attendance/AttendanceDetailPage.vue
  src/views/attendance/AttendanceListPage.vue
  src/views/orgstructure/ProfilePage.vue
Labels: :sparkles: enhancement
